### ISSUE TITLE
find model error

### ISSUE THREAD

**Issue by Piller4F** [MMD-Blender/blender_mmd_tools_append#102]
Python: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/UuuNyaa/blender_mmd_assets/issues?state=open&milestone=1&labels=Official&per_page=100&page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\operators.py", line 32, in execute
    AssetUpdater.fetch_assets_json_by_query(self.repo, self.query),
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\asset_search\assets.py", line 267, in fetch_assets_json_by_query
    return cat_asset_json.wrap_assets(cat_asset_json.fetch_assets(session, repo, query))
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\externals\blender_mmd_assets\cat_asset_json.py", line 208, in fetch_assets
    issues = fetch_issues(session, repo, query)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\mmd_uuunyaa_tools\externals\blender_mmd_assets\cat_asset_json.py", line 171, in fetch_issues
    response = session.get(
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.93LTS_2.93.118.0_x64__ppwjx1n5r4v9t\Blender\2.93\python\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/UuuNyaa/blender_mmd_assets/issues?state=open&milestone=1&labels=Official&per_page=100&page=1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))

location: <unknown location>:-1

**Comment by linlinsama123** [comment]
how to fix it ?

**Comment by linlinsama123** [comment]
![Uploading Screenshot 2023-12-09 190612.png…]()

**Comment by linlinsama123** [comment]
![Screenshot 2023-12-09 190612](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/assets/153383782/d00a2fb7-e0af-402e-96c8-3fb2cf6d7c4d)
![Screenshot 2023-12-09 190305](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/assets/153383782/3542af4e-b3fd-40e5-bdb8-19c67d38841d)
how to fix this ?

**Comment by UuuNyaa** [comment]
[MMD Tools](https://github.com/UuuNyaa/blender_mmd_tools) is not yet compatible with Blender 4.x.
By the way, MMD Tools and MMD **UuuNyaa** Tools are different add-ons.

**Comment by ulyssas** [comment]
@Piller4F To me it looks like Microsoft Store issue (WindowsApps). It looks like it doesn't have network permissions, so it will fail. You should use other distributions (exe/msi install or Steam for autoupdate).

@linlinsama123 MMD Tools 4.x exists now, so this issue is fixed.
