### ISSUE TITLE
Shader Not found

### ISSUE THREAD

**Issue by kiraaau** [MMD-Blender/blender_mmd_tools_append#118]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\operators\fileio.py", line 163, in execute
    self._do_execute(context)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\operators\fileio.py", line 182, in _do_execute
    importer_cls().execute(
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\pmx\importer.py", line 845, in execute
    self.__importMaterials()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\pmx\importer.py", line 557, in __importMaterials
    texture_slot = fnMat.create_texture(self.__textureTable[i.texture])
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 420, in create_texture
    texture = self.__create_texture_node('mmd_base_tex', filepath, (-4, -1))
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 508, in __create_texture_node
    self.__update_shader_nodes()
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 666, in __update_shader_nodes
    if not node_shader.outputs['Shader'].is_linked:
KeyError: 'bpy_prop_collection[key]: key "Shader" not found'

the characters are broken, they become small vertices when imported into blender|
![image](https://github.com/UuuNyaa/blender_mmd_uuunyaa_tools/assets/129415381/bf37f26b-bb79-4537-9bb1-9d82fc9a7dc2)

**Comment by jensentsts** [comment]
Same in 3.4.

**Comment by ulyssas** [comment]
I'm not sure about 3.4 though. But this is MMD Tools issue, not Append (UuuNyaa Tools) issue.
