### ISSUE TITLE
MMD uuunyaa tools cannot install

### ISSUE THREAD

**Issue by ImKoshitan** [MMD-Blender/blender_mmd_tools_append#132]
Traceback (most recent call last):
  File "D:\Steam\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\converters\armatures\__init__.py", line 5, in <module>
    from mmd_uuunyaa_tools.converters.armatures.autorig import *
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\converters\armatures\autorig.py", line 10, in <module>
    from mmd_uuunyaa_tools.converters.armatures.mmd import (MMDArmatureObject,
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\converters\armatures\mmd.py", line 11, in <module>
    from mmd_uuunyaa_tools.editors.armatures import ArmatureEditor
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\editors\armatures.py", line 316, in <module>
    class ArmatureEditor(EditBoneEditor, PoseBoneEditor):
  File "C:\Users\Gigabyte\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_uuunyaa_tools\editors\armatures.py", line 333, in ArmatureEditor
    def pose_bone_groups(self) -> bpy.types.BoneGroups:
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'BoneGroups'

**AttributeError: 'module' object has no attribute 'BoneGroups'**
What should i do?

**Comment by Naileon** [comment]
mee too

**Comment by haidonovan** [comment]
me too I can't install on blender version 3.6 without lts

**Comment by ulyssas** [comment]
MMD Tools Append (formerly MMD UuuNyaa Tools) will never support Blender 4.0 and 4.1, since they are not LTS versions.
MMD Tools Append 4.x will support Blender 4.2 and later.

This is the table of matching versions of Blender, MMD Tools and MMD Tools Append (formerly UuuNyaa Tools)
| Blender LTS Version | MMD Tools Version | MMD UuuNyaa Tools Version |
| ------------------- | ----------------- | ------------------------- |
| Blender 4.2 & 4.5   | MMD Tools v4.x    | MMD Tools Append v4.x     |
| Blender 3.6         | MMD Tools v2.10.3 | UuuNyaa Tools v1.8.0      |
| Blender 2.93        | MMD Tools v2.10.3 | UuuNyaa Tools v1.7.2      |
| Blender 2.83        | MMD Tools v2.5.1  | UuuNyaa Tools v1.6.0      |

**IMPORTANT!!! MMD Tools Append v4.x is still experimental, and you should wait for full release on Blender Extensions.**
